"""POAgent — renders Purchase Order PDFs and dispatches to awarded vendors."""

import json
import os
from datetime import UTC, datetime
from typing import Any

from aeros.agents.base import AgentContext, AgentResult, BaseAgent
from aeros.channels.email_out import send_po_email
from aeros.models.award import Award, PurchaseOrder
from aeros.models.rfx import RFxRun
from aeros.models.sku import SKU
from aeros.models.vendor import Vendor

PO_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
body {{ font-family: 'Helvetica', sans-serif; margin: 40px; color: #18181b; }}
.header {{
  display: flex; justify-content: space-between;
  align-items: flex-start; margin-bottom: 30px;
}}
.logo {{ font-size: 28px; font-weight: bold; color: #4f46e5; }}
.po-info {{ text-align: right; }}
.po-number {{ font-size: 20px; font-weight: bold; }}
.section {{ margin: 20px 0; }}
.section-title {{
  font-size: 14px; font-weight: 600; color: #71717a;
  text-transform: uppercase; letter-spacing: 1px;
  margin-bottom: 8px;
}}
table {{ width: 100%; border-collapse: collapse; margin-top: 8px; }}
th {{
  background: #f4f4f5; padding: 10px 12px;
  text-align: left; font-size: 12px; color: #52525b;
  border-bottom: 2px solid #e4e4e7;
}}
td {{ padding: 10px 12px; border-bottom: 1px solid #e4e4e7; font-size: 13px; }}
.total-row {{ font-weight: bold; background: #fafafa; }}
.footer {{
  margin-top: 40px; padding-top: 20px;
  border-top: 1px solid #e4e4e7;
  font-size: 11px; color: #a1a1aa;
}}
</style>
</head>
<body>
<div class="header">
    <div class="logo">AEROS</div>
    <div class="po-info">
        <div class="po-number">PO #{po_number}</div>
        <div>Date: {date}</div>
    </div>
</div>

<div class="section">
    <div class="section-title">Vendor</div>
    <p><strong>{vendor_name}</strong><br>{vendor_email}</p>
</div>

<div class="section">
    <div class="section-title">Order Details</div>
    <table>
        <thead>
            <tr>
                <th>Item</th>
                <th>Qty</th>
                <th>Unit</th>
                <th>Unit Price</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            {line_items_html}
        </tbody>
        <tfoot>
            <tr class="total-row">
                <td colspan="4" style="text-align: right;">Total</td>
                <td>{currency} {total_amount}</td>
            </tr>
        </tfoot>
    </table>
</div>

<div class="section">
    <div class="section-title">Terms</div>
    <p>Payment: {payment_terms}<br>
    Delivery: {delivery_terms}<br>
    Validity: {validity_days} days</p>
</div>

<div class="footer">
    Generated by AEROS Procurement System | {date}
</div>
</body>
</html>
"""


class POAgent(BaseAgent):
    name = "po"

    async def run(self, ctx: AgentContext, user_input: str) -> AgentResult:
        award_id = int(user_input)
        award = ctx.session.get(Award, award_id)
        if not award:
            return AgentResult(message="Award not found", success=False)

        rfx = ctx.session.get(RFxRun, award.rfx_id)
        if not rfx:
            return AgentResult(message="RFx not found", success=False)

        decisions = json.loads(award.decisions_json)

        # Group decisions by vendor
        vendor_decisions: dict[int, list[Any]] = {}
        for d in decisions:
            vid = d["vendor_id"]
            if vid not in vendor_decisions:
                vendor_decisions[vid] = []
            vendor_decisions[vid].append(d)

        po_numbers = []
        for vendor_id, items in vendor_decisions.items():
            vendor = ctx.session.get(Vendor, vendor_id)
            if not vendor:
                continue

            po_number = f"PO-{rfx.id}-{vendor_id}-{datetime.now(UTC).strftime('%Y%m%d')}"

            # Build line items HTML
            total = 0.0
            li_html_parts = []
            for item in items:
                sku = ctx.session.get(SKU, item.get("sku_id", 0))
                name = sku.name if sku else f"Item {item.get('line_item_id', '')}"
                qty = item.get("qty", 0)
                price = item.get("unit_price", 0)
                line_total = qty * price
                total += line_total
                unit = sku.unit if sku else ""
                li_html_parts.append(
                    f"<tr><td>{name}</td><td>{qty}</td><td>{unit}</td>"
                    f"<td>{rfx.currency_for_this_rfx} {price:.2f}</td>"
                    f"<td>{rfx.currency_for_this_rfx} {line_total:.2f}</td></tr>"
                )

            html = PO_HTML_TEMPLATE.format(
                po_number=po_number,
                date=datetime.now(UTC).strftime("%Y-%m-%d"),
                vendor_name=vendor.name,
                vendor_email=vendor.primary_email,
                line_items_html="\n".join(li_html_parts),
                currency=rfx.currency_for_this_rfx,
                total_amount=f"{total:.2f}",
                payment_terms=rfx.payment_terms_for_this_rfx,
                delivery_terms=rfx.delivery_terms_for_this_rfx,
                validity_days=rfx.quote_validity_days_for_this_rfx,
            )

            # Render PDF
            po_dir = os.path.join("data", "po")
            os.makedirs(po_dir, exist_ok=True)
            pdf_path = os.path.join(po_dir, f"{po_number}.pdf")

            try:
                from weasyprint import HTML

                HTML(string=html).write_pdf(pdf_path)
            except Exception:
                # Fallback: save HTML
                pdf_path = os.path.join(po_dir, f"{po_number}.html")
                with open(pdf_path, "w") as f:
                    f.write(html)

            # Create PurchaseOrder record
            po = PurchaseOrder(
                award_id=award_id,
                vendor_id=vendor_id,
                po_number=po_number,
                total_amount=total,
                currency=rfx.currency_for_this_rfx,
                terms_json=json.dumps(
                    {
                        "payment": rfx.payment_terms_for_this_rfx,
                        "delivery": rfx.delivery_terms_for_this_rfx,
                    }
                ),
                line_items_json=json.dumps(items),
                pdf_path=pdf_path,
            )
            ctx.session.add(po)

            # Email PO to vendor
            await send_po_email(
                to_email=vendor.primary_email,
                vendor_name=vendor.name,
                po_number=po_number,
                pdf_path=pdf_path,
            )

            po_numbers.append(po_number)

        ctx.session.commit()

        return AgentResult(
            message=f"Generated {len(po_numbers)} Purchase Order(s): {', '.join(po_numbers)}",
            data={"po_numbers": po_numbers},
            success=True,
        )
