"""add observability tables

Revision ID: 5dcda45063d9
Revises: 94eaeaddc8fe
Create Date: 2026-05-27 22:46:29.253903
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '5dcda45063d9'
down_revision: Union[str, None] = '94eaeaddc8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentrunlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rfx_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('input_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_llm_calls', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('tool_calls_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentrunlog_trace_id'), 'agentrunlog', ['trace_id'], unique=False)
    op.create_table('channeleventlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rfx_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channeleventlog_trace_id'), 'channeleventlog', ['trace_id'], unique=False)
    op.create_table('llmcalllog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rfx_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llmcalllog_agent_run_id'), 'llmcalllog', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_llmcalllog_trace_id'), 'llmcalllog', ['trace_id'], unique=False)
    op.create_table('pipelinereport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rfx_id', sa.Integer(), nullable=True),
    sa.Column('pipeline_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('total_duration_ms', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelinereport_trace_id'), 'pipelinereport', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipelinereport_trace_id'), table_name='pipelinereport')
    op.drop_table('pipelinereport')
    op.drop_index(op.f('ix_llmcalllog_trace_id'), table_name='llmcalllog')
    op.drop_index(op.f('ix_llmcalllog_agent_run_id'), table_name='llmcalllog')
    op.drop_table('llmcalllog')
    op.drop_index(op.f('ix_channeleventlog_trace_id'), table_name='channeleventlog')
    op.drop_table('channeleventlog')
    op.drop_index(op.f('ix_agentrunlog_trace_id'), table_name='agentrunlog')
    op.drop_table('agentrunlog')
    # ### end Alembic commands ###
