"""initial schema

Revision ID: 94eaeaddc8fe
Revises: 
Create Date: 2026-05-26 21:25:49.008606
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '94eaeaddc8fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('before_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('after_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_table('llmcache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llmcache_content_hash'), 'llmcache', ['content_hash'], unique=False)
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('BUYER', 'VENDOR', name='orgtype'), nullable=False),
    sa.Column('gst_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pack_size', sa.Float(), nullable=True),
    sa.Column('reorder_point', sa.Float(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('last_vendor_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aliases_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gst_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sku_code'), 'sku', ['code'], unique=False)
    op.create_index(op.f('ix_sku_org_id'), 'sku', ['org_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('BUYER', 'VENDOR', 'ADMIN', name='role'), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telegram_chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notification_prefs_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language_pref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'PENDING', name='userstatus'), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('related_entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('related_entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('rfxrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('RFQ', 'RFI', 'RFP', name='rfxtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFTING', 'AWAITING_APPROVAL', 'DISPATCHED', 'COLLECTING', 'COMPARING', 'AWARDED', 'CLOSED', 'CANCELLED', name='rfxstatus'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivery_window_start', sa.DateTime(), nullable=True),
    sa.Column('delivery_window_end', sa.DateTime(), nullable=True),
    sa.Column('response_deadline', sa.DateTime(), nullable=True),
    sa.Column('payment_terms_for_this_rfx', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivery_terms_for_this_rfx', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quote_validity_days_for_this_rfx', sa.Integer(), nullable=False),
    sa.Column('currency_for_this_rfx', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tax_treatment_for_this_rfx', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes_for_vendors', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfxrun_buyer_id'), 'rfxrun', ['buyer_id'], unique=False)
    op.create_table('userdefaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_terms_default', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivery_terms_default', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quote_validity_days_default', sa.Integer(), nullable=False),
    sa.Column('currency_default', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tax_treatment_default', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivery_window_default', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auto_reminder_hours_before_deadline', sa.Integer(), nullable=False),
    sa.Column('escalation_emails_csv', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userdefaults_user_id'), 'userdefaults', ['user_id'], unique=True)
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owning_buyer_org_id', sa.Integer(), nullable=False),
    sa.Column('vendor_user_id', sa.Integer(), nullable=True),
    sa.Column('vendor_org_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telegram_chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_ids_csv', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.Column('preferred_rank', sa.Integer(), nullable=False),
    sa.Column('kyc_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='kycstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owning_buyer_org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['vendor_org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['vendor_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_owning_buyer_org_id'), 'vendor', ['owning_buyer_org_id'], unique=False)
    op.create_table('award',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfx_id', sa.Integer(), nullable=False),
    sa.Column('decisions_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.Column('awarded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('po_pdf_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('po_sent_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('po_sent_message_ids_csv', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['awarded_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rfx_id'], ['rfxrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_award_rfx_id'), 'award', ['rfx_id'], unique=False)
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfx_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('line_items_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_quote', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lead_time_hours', sa.Float(), nullable=True),
    sa.Column('payment_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delivery_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('validity_until', sa.DateTime(), nullable=True),
    sa.Column('tax_treatment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gst_pct', sa.Float(), nullable=True),
    sa.Column('additional_charges_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vendor_remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extraction_confidence_overall', sa.Float(), nullable=False),
    sa.Column('source_message_ids_csv', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_extraction_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('manual_overrides_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('superseded_by_offer_id', sa.Integer(), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('total_quote_inr', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rfx_id'], ['rfxrun.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_rfx_id'), 'offer', ['rfx_id'], unique=False)
    op.create_index(op.f('ix_offer_vendor_id'), 'offer', ['vendor_id'], unique=False)
    op.create_table('rfxlineitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfx_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit_override', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('target_lead_time_hours', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['rfx_id'], ['rfxrun.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfxlineitem_rfx_id'), 'rfxlineitem', ['rfx_id'], unique=False)
    op.create_table('rfxvendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfx_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('correlation_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('INVITED', 'VIEWED', 'QUOTED', 'DECLINED', 'EXPIRED', name='rfxvendorstatus'), nullable=False),
    sa.Column('decline_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('declined_at', sa.DateTime(), nullable=True),
    sa.Column('reminders_sent_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['rfx_id'], ['rfxrun.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfxvendor_rfx_id'), 'rfxvendor', ['rfx_id'], unique=False)
    op.create_index(op.f('ix_rfxvendor_vendor_id'), 'rfxvendor', ['vendor_id'], unique=False)
    op.create_table('thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfx_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rfx_id'], ['rfxrun.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_rfx_id'), 'thread', ['rfx_id'], unique=False)
    op.create_index(op.f('ix_thread_vendor_id'), 'thread', ['vendor_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('sender_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_html', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_thread_id'), 'message', ['thread_id'], unique=False)
    op.create_table('purchaseorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('po_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('terms_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line_items_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pdf_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['award_id'], ['award.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchaseorder_award_id'), 'purchaseorder', ['award_id'], unique=False)
    op.create_index(op.f('ix_purchaseorder_po_number'), 'purchaseorder', ['po_number'], unique=False)
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extraction_status', sa.Enum('PENDING', 'EXTRACTED', 'FAILED', name='extractionstatus'), nullable=False),
    sa.Column('extraction_attempts', sa.Integer(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_message_id'), 'attachment', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachment_message_id'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_index(op.f('ix_purchaseorder_po_number'), table_name='purchaseorder')
    op.drop_index(op.f('ix_purchaseorder_award_id'), table_name='purchaseorder')
    op.drop_table('purchaseorder')
    op.drop_index(op.f('ix_message_thread_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_thread_vendor_id'), table_name='thread')
    op.drop_index(op.f('ix_thread_rfx_id'), table_name='thread')
    op.drop_table('thread')
    op.drop_index(op.f('ix_rfxvendor_vendor_id'), table_name='rfxvendor')
    op.drop_index(op.f('ix_rfxvendor_rfx_id'), table_name='rfxvendor')
    op.drop_table('rfxvendor')
    op.drop_index(op.f('ix_rfxlineitem_rfx_id'), table_name='rfxlineitem')
    op.drop_table('rfxlineitem')
    op.drop_index(op.f('ix_offer_vendor_id'), table_name='offer')
    op.drop_index(op.f('ix_offer_rfx_id'), table_name='offer')
    op.drop_table('offer')
    op.drop_index(op.f('ix_award_rfx_id'), table_name='award')
    op.drop_table('award')
    op.drop_index(op.f('ix_vendor_owning_buyer_org_id'), table_name='vendor')
    op.drop_table('vendor')
    op.drop_index(op.f('ix_userdefaults_user_id'), table_name='userdefaults')
    op.drop_table('userdefaults')
    op.drop_index(op.f('ix_rfxrun_buyer_id'), table_name='rfxrun')
    op.drop_table('rfxrun')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_sku_org_id'), table_name='sku')
    op.drop_index(op.f('ix_sku_code'), table_name='sku')
    op.drop_table('sku')
    op.drop_table('organization')
    op.drop_index(op.f('ix_llmcache_content_hash'), table_name='llmcache')
    op.drop_table('llmcache')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    op.drop_table('auditlog')
    # ### end Alembic commands ###
