"""Integration tests for multi-format vendor quote uploads.

Uploads each supported file format through the vendor API endpoint and
verifies:
  1. Upload succeeds (HTTP 200, returns message_id + attachment_id)
  2. The extraction pipeline is invoked with the correct MIME type
  3. An Offer is created from the extraction result

Fixture files live in tests/fixtures/vendor_quotes/ and are generated by
generate_fixtures.py (CSV, XLSX, PDF, DOCX, PNG, TXT, HTML).
"""

import io
import json
import os
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock, patch

import pytest

from aeros.ai.base import ChatResponse
from aeros.models.offer import Offer
from aeros.models.organization import OrgType, Organization
from aeros.models.rfx import Attachment, RFxVendor, RFxVendorStatus, Thread
from aeros.models.sku import Category, SKU
from aeros.models.user import Role, User
from aeros.models.user_defaults import UserDefaults
from aeros.models.vendor import Vendor
from aeros.services.auth_service import hash_password

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

FIXTURES_DIR = Path(__file__).resolve().parent.parent / "fixtures" / "vendor_quotes"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _mock_chat_response(content: str) -> ChatResponse:
    """Build a ChatResponse matching the AI provider contract."""
    return ChatResponse(
        content=content,
        input_tokens=100,
        output_tokens=50,
        model="mock-model",
        finish_reason="stop",
    )


def _extraction_json(
    sku_name: str = "Full Cream Milk",
    qty: float = 200,
    unit: str = "ltr",
    unit_price: float = 56.0,
    total: float = 11200.0,
    total_quote: float = 46100.0,
) -> str:
    """Return realistic extraction JSON for mocked LLM responses."""
    return json.dumps({
        "line_items": [
            {
                "sku_name": sku_name,
                "qty": qty,
                "unit": unit,
                "unit_price": unit_price,
                "total": total,
                "confidence_per_field": {"unit_price": 0.95, "qty": 0.98},
            },
        ],
        "total_quote": total_quote,
        "currency": "INR",
        "payment_terms": "NET15",
        "delivery_terms": "doorstep",
        "lead_time_hours": 24,
        "confidence_overall": 0.92,
    })


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def category(session) -> Category:
    """A product category for test SKUs."""
    cat = Category(name="Dairy", sort_order=1)
    session.add(cat)
    session.commit()
    session.refresh(cat)
    return cat


@pytest.fixture
def sku(session, buyer_org, category) -> SKU:
    """A single SKU for the RFx line items."""
    sku = SKU(
        org_id=buyer_org.id,
        code="DAI-001",
        name="Full Cream Milk",
        category_id=category.id,
        unit="ltr",
        last_price=55.0,
    )
    session.add(sku)
    session.commit()
    session.refresh(sku)
    return sku


@pytest.fixture
def vendor_org(session) -> Organization:
    """Vendor organization."""
    org = Organization(name="FormatTestVendorOrg", type=OrgType.VENDOR)
    session.add(org)
    session.commit()
    session.refresh(org)
    return org


@pytest.fixture
def vendor_record(session, vendor_org, buyer_org) -> tuple[User, Vendor]:
    """A vendor user with both User and Vendor records."""
    user = User(
        email="format-vendor@test.com",
        password_hash=hash_password("test123"),
        role=Role.VENDOR,
        display_name="Format Test Vendor",
        org_id=vendor_org.id,
    )
    session.add(user)
    session.commit()
    session.refresh(user)

    vendor = Vendor(
        owning_buyer_org_id=buyer_org.id,
        vendor_user_id=user.id,
        vendor_org_id=vendor_org.id,
        name="Format Test Vendor Co",
        primary_email="format-vendor@test.com",
    )
    session.add(vendor)
    session.commit()
    session.refresh(vendor)
    return user, vendor


@pytest.fixture
def dispatched_rfx(session, buyer_user, sku, vendor_record):
    """An RFx in DISPATCHED status with a vendor thread ready for uploads."""
    from aeros.services import rfx_service

    _, vendor = vendor_record

    rfx = rfx_service.create_rfx(
        session,
        buyer_id=buyer_user.id,
        title="Multi-Format Upload Test RFx",
    )
    rfx_service.add_line_items(session, rfx.id, [
        {"sku_id": sku.id, "qty": 200, "unit_override": "ltr", "target_price": 55.0},
    ])

    rfx_service.invite_vendor(session, rfx.id, vendor.id, "token-hash-fmt-test")
    rfx_service.dispatch_rfx(session, rfx.id, buyer_user.id)
    return rfx


@pytest.fixture
def vendor_auth_client(client, vendor_record):
    """TestClient authenticated as the format-test vendor."""
    user, _ = vendor_record
    resp = client.post(
        "/api/auth/login",
        json={"email": "format-vendor@test.com", "password": "test123"},
    )
    assert resp.status_code == 200
    return client


@pytest.fixture
def mock_ai_provider() -> AsyncMock:
    """A mock chat provider that returns valid extraction JSON."""
    provider = AsyncMock()
    provider.chat.return_value = _mock_chat_response(_extraction_json())
    return provider


# ---------------------------------------------------------------------------
# Test class
# ---------------------------------------------------------------------------


class TestFormatUploads:
    """Upload each fixture format via the vendor API with mocked AI."""

    # -- CSV ----------------------------------------------------------------

    def test_upload_csv(
        self,
        vendor_auth_client,
        dispatched_rfx,
        mock_ai_provider,
        session,
    ) -> None:
        """CSV file upload should succeed and trigger extraction."""
        filepath = FIXTURES_DIR / "quote_freshfarm.csv"
        assert filepath.exists(), f"Fixture missing: {filepath}"

        with (
            open(filepath, "rb") as f,
            patch("aeros.ai.factory.get_chat_provider", return_value=mock_ai_provider),
            patch("aeros.ai.factory.get_vision_provider", return_value=None),
        ):
            resp = vendor_auth_client.post(
                f"/api/vendor/rfx/{dispatched_rfx.id}/upload",
                files={"file": ("quote_freshfarm.csv", f, "text/csv")},
            )

        assert resp.status_code == 200
        data = resp.json()
        assert "message_id" in data
        assert "attachment_id" in data
        assert data["filename"] == "quote_freshfarm.csv"

        # Verify extraction was called (2 calls: first pass + gleaning)
        assert mock_ai_provider.chat.call_count == 2

    # -- XLSX ---------------------------------------------------------------

    def test_upload_xlsx(
        self,
        vendor_auth_client,
        dispatched_rfx,
        mock_ai_provider,
        session,
    ) -> None:
        """Excel file upload should succeed and trigger extraction."""
        filepath = FIXTURES_DIR / "quote_metro.xlsx"
        assert filepath.exists(), f"Fixture missing: {filepath}"

        with (
            open(filepath, "rb") as f,
            patch("aeros.ai.factory.get_chat_provider", return_value=mock_ai_provider),
            patch("aeros.ai.factory.get_vision_provider", return_value=None),
        ):
            resp = vendor_auth_client.post(
                f"/api/vendor/rfx/{dispatched_rfx.id}/upload",
                files={
                    "file": (
                        "quote_metro.xlsx",
                        f,
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    )
                },
            )

        assert resp.status_code == 200
        data = resp.json()
        assert "message_id" in data
        assert "attachment_id" in data
        assert data["filename"] == "quote_metro.xlsx"
        assert mock_ai_provider.chat.call_count == 2

    # -- PDF ----------------------------------------------------------------

    def test_upload_pdf(
        self,
        vendor_auth_client,
        dispatched_rfx,
        mock_ai_provider,
        session,
    ) -> None:
        """PDF file upload should succeed and trigger extraction."""
        filepath = FIXTURES_DIR / "quote_bakery.pdf"
        assert filepath.exists(), f"Fixture missing: {filepath}"

        with (
            open(filepath, "rb") as f,
            patch("aeros.ai.factory.get_chat_provider", return_value=mock_ai_provider),
            patch("aeros.ai.factory.get_vision_provider", return_value=None),
        ):
            resp = vendor_auth_client.post(
                f"/api/vendor/rfx/{dispatched_rfx.id}/upload",
                files={"file": ("quote_bakery.pdf", f, "application/pdf")},
            )

        assert resp.status_code == 200
        data = resp.json()
        assert "message_id" in data
        assert "attachment_id" in data
        assert data["filename"] == "quote_bakery.pdf"
        assert mock_ai_provider.chat.call_count == 2

    # -- DOCX ---------------------------------------------------------------

    def test_upload_docx(
        self,
        vendor_auth_client,
        dispatched_rfx,
        mock_ai_provider,
        session,
    ) -> None:
        """Word document upload should succeed and trigger extraction."""
        filepath = FIXTURES_DIR / "quote_kirana.docx"
        assert filepath.exists(), f"Fixture missing: {filepath}"

        mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        with (
            open(filepath, "rb") as f,
            patch("aeros.ai.factory.get_chat_provider", return_value=mock_ai_provider),
            patch("aeros.ai.factory.get_vision_provider", return_value=None),
        ):
            resp = vendor_auth_client.post(
                f"/api/vendor/rfx/{dispatched_rfx.id}/upload",
                files={"file": ("quote_kirana.docx", f, mime)},
            )

        assert resp.status_code == 200
        data = resp.json()
        assert "message_id" in data
        assert "attachment_id" in data
        assert data["filename"] == "quote_kirana.docx"
        assert mock_ai_provider.chat.call_count == 2

    # -- PNG (image) --------------------------------------------------------

    def test_upload_png(
        self,
        vendor_auth_client,
        dispatched_rfx,
        mock_ai_provider,
        session,
    ) -> None:
        """PNG image upload should succeed and trigger extraction."""
        filepath = FIXTURES_DIR / "quote_greenvalley.png"
        assert filepath.exists(), f"Fixture missing: {filepath}"

        mock_vision = AsyncMock()
        from aeros.ai.base import VisionResponse

        mock_vision.vision.return_value = VisionResponse(
            content="Organic Spinach 60/kg, Organic Tomato 45/kg"
        )

        with (
            open(filepath, "rb") as f,
            patch("aeros.ai.factory.get_chat_provider", return_value=mock_ai_provider),
            patch("aeros.ai.factory.get_vision_provider", return_value=mock_vision),
        ):
            resp = vendor_auth_client.post(
                f"/api/vendor/rfx/{dispatched_rfx.id}/upload",
                files={"file": ("quote_greenvalley.png", f, "image/png")},
            )

        assert resp.status_code == 200
        data = resp.json()
        assert "message_id" in data
        assert "attachment_id" in data
        assert data["filename"] == "quote_greenvalley.png"
        # Vision provider should have been called for image extraction
        mock_vision.vision.assert_called_once()
        assert mock_ai_provider.chat.call_count == 2

    # -- Plain text ---------------------------------------------------------

    def test_upload_txt(
        self,
        vendor_auth_client,
        dispatched_rfx,
        mock_ai_provider,
        session,
    ) -> None:
        """Plain text file upload should succeed and trigger extraction."""
        filepath = FIXTURES_DIR / "quote_daily.txt"
        assert filepath.exists(), f"Fixture missing: {filepath}"

        with (
            open(filepath, "rb") as f,
            patch("aeros.ai.factory.get_chat_provider", return_value=mock_ai_provider),
            patch("aeros.ai.factory.get_vision_provider", return_value=None),
        ):
            resp = vendor_auth_client.post(
                f"/api/vendor/rfx/{dispatched_rfx.id}/upload",
                files={"file": ("quote_daily.txt", f, "text/plain")},
            )

        assert resp.status_code == 200
        data = resp.json()
        assert "message_id" in data
        assert "attachment_id" in data
        assert data["filename"] == "quote_daily.txt"
        assert mock_ai_provider.chat.call_count == 2

    # -- HTML ---------------------------------------------------------------

    def test_upload_html(
        self,
        vendor_auth_client,
        dispatched_rfx,
        mock_ai_provider,
        session,
    ) -> None:
        """HTML file upload should succeed and trigger extraction."""
        filepath = FIXTURES_DIR / "quote_annapurna.html"
        assert filepath.exists(), f"Fixture missing: {filepath}"

        with (
            open(filepath, "rb") as f,
            patch("aeros.ai.factory.get_chat_provider", return_value=mock_ai_provider),
            patch("aeros.ai.factory.get_vision_provider", return_value=None),
        ):
            resp = vendor_auth_client.post(
                f"/api/vendor/rfx/{dispatched_rfx.id}/upload",
                files={"file": ("quote_annapurna.html", f, "text/html")},
            )

        assert resp.status_code == 200
        data = resp.json()
        assert "message_id" in data
        assert "attachment_id" in data
        assert data["filename"] == "quote_annapurna.html"
        assert mock_ai_provider.chat.call_count == 2


class TestExtractionMimeRouting:
    """Verify that the upload endpoint passes the correct MIME type to
    the extraction pipeline for each file format."""

    @pytest.mark.parametrize(
        "fixture_file,mime_type",
        [
            ("quote_freshfarm.csv", "text/csv"),
            (
                "quote_metro.xlsx",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            ),
            ("quote_bakery.pdf", "application/pdf"),
            (
                "quote_kirana.docx",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            ),
            ("quote_greenvalley.png", "image/png"),
            ("quote_daily.txt", "text/plain"),
            ("quote_annapurna.html", "text/html"),
        ],
        ids=["csv", "xlsx", "pdf", "docx", "png", "txt", "html"],
    )
    def test_mime_type_passed_to_extraction(
        self,
        vendor_auth_client,
        dispatched_rfx,
        session,
        fixture_file: str,
        mime_type: str,
    ) -> None:
        """The attachment stored in the DB should have the correct MIME type."""
        filepath = FIXTURES_DIR / fixture_file
        assert filepath.exists(), f"Fixture missing: {filepath}"

        mock_provider = AsyncMock()
        mock_provider.chat.return_value = _mock_chat_response(_extraction_json())

        mock_vision = AsyncMock()
        from aeros.ai.base import VisionResponse

        mock_vision.vision.return_value = VisionResponse(
            content="Extracted text from image"
        )

        with (
            open(filepath, "rb") as f,
            patch("aeros.ai.factory.get_chat_provider", return_value=mock_provider),
            patch("aeros.ai.factory.get_vision_provider", return_value=mock_vision),
        ):
            resp = vendor_auth_client.post(
                f"/api/vendor/rfx/{dispatched_rfx.id}/upload",
                files={"file": (fixture_file, f, mime_type)},
            )

        assert resp.status_code == 200
        data = resp.json()

        # Verify the Attachment record has the correct MIME type
        from sqlmodel import select

        att = session.exec(
            select(Attachment).where(Attachment.id == data["attachment_id"])
        ).first()
        assert att is not None
        assert att.mime_type == mime_type


class TestOfferCreation:
    """Verify that a successful extraction creates an Offer for each format."""

    @pytest.mark.parametrize(
        "fixture_file,mime_type",
        [
            ("quote_freshfarm.csv", "text/csv"),
            (
                "quote_metro.xlsx",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            ),
            ("quote_bakery.pdf", "application/pdf"),
            (
                "quote_kirana.docx",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            ),
            ("quote_greenvalley.png", "image/png"),
            ("quote_daily.txt", "text/plain"),
            ("quote_annapurna.html", "text/html"),
        ],
        ids=["csv", "xlsx", "pdf", "docx", "png", "txt", "html"],
    )
    def test_offer_created_after_upload(
        self,
        vendor_auth_client,
        dispatched_rfx,
        vendor_record,
        session,
        fixture_file: str,
        mime_type: str,
    ) -> None:
        """Upload + extraction should produce an Offer linked to the RFx."""
        _, vendor = vendor_record
        filepath = FIXTURES_DIR / fixture_file
        assert filepath.exists(), f"Fixture missing: {filepath}"

        mock_provider = AsyncMock()
        mock_provider.chat.return_value = _mock_chat_response(_extraction_json())

        mock_vision = AsyncMock()
        from aeros.ai.base import VisionResponse

        mock_vision.vision.return_value = VisionResponse(
            content="Extracted text from image"
        )

        with (
            open(filepath, "rb") as f,
            patch("aeros.ai.factory.get_chat_provider", return_value=mock_provider),
            patch("aeros.ai.factory.get_vision_provider", return_value=mock_vision),
        ):
            resp = vendor_auth_client.post(
                f"/api/vendor/rfx/{dispatched_rfx.id}/upload",
                files={"file": (fixture_file, f, mime_type)},
            )

        assert resp.status_code == 200

        # Check that an Offer was created
        from sqlmodel import select

        offer = session.exec(
            select(Offer).where(
                Offer.rfx_id == dispatched_rfx.id,
                Offer.vendor_id == vendor.id,
            )
        ).first()
        assert offer is not None, f"No Offer created for {fixture_file}"
        assert offer.total_quote == 46100.0
        assert offer.currency == "INR"
        assert offer.payment_terms == "NET15"

        # Verify vendor lane status updated to QUOTED
        rv = session.exec(
            select(RFxVendor).where(
                RFxVendor.rfx_id == dispatched_rfx.id,
                RFxVendor.vendor_id == vendor.id,
            )
        ).first()
        assert rv is not None
        assert rv.status == RFxVendorStatus.QUOTED
